### ISSUE TITLE
improved use of the built-in attenuator

### ISSUE THREAD

**Issue by F4HTB** [ik1xpv/ExtIO_sddc#109]
Hello, 

Receiver: RX888
Software: HDSDR v2.80 installer with OmniRig V2 support. (March 19, 2020)
DLL: ExtIO_sddc_v1.1RC1.zip from https://github.com/ik1xpv/ExtIO_sddc/releases/download/v1.1/ExtIO_sddc_v1.1RC1.zip
OS: Windows 10 1909

When we use the db RF selection in the (F8) SDR-Device.
First time we see -19 or -18db RF.
I have increase to 0db but i can comme back to -9 only.
Unable to set less.

On the main windows of hdsdr, when it is set to -9, i see RF-10.
When i set the gain here, i can set rf-20 and the extIO_sddc.dll screen is set to -19db RF.

I dont no if it's hdsdr or the dll who has a bug.

Many Thanks.

**Comment by ik1xpv** [comment]
You are fully right.
At the moment please use the HDSDR one we will try to fix the dll dialog box.
I made the same test on BBF103 and the behaviour is the same of RX888
While with RF103 I have a 1 dB mismatch between HDSDR and EstIO dialog.
Thanks for the precise description of the bug.  We will try to solve ;-)

**Comment by howard0su** [comment]
Issues are fixed.
