### ISSUE TITLE
Use frequency correction from hdsdr not work correctly

### ISSUE THREAD

**Issue by F4HTB** [ik1xpv/ExtIO_sddc#110]
Hello, 

Receiver: RX888
Software: HDSDR v2.80 installer with OmniRig V2 support. (March 19, 2020)
DLL: ExtIO_sddc_v1.1RC1.zip from https://github.com/ik1xpv/ExtIO_sddc/releases/download/v1.1/ExtIO_sddc_v1.1RC1.zip
OS: Windows 10 1909

I have try to set the ppm correction compared to the 9.996MHZ beacon.
I have set the signal to hear on 1khz BF.
The frequency in hdsdr is 9994331hz.
When i go to calibration settings, i have :
Current Tune Frequency [hz] 9994331,00
Correct Tune Frequency: 9995000

When i clic on "Calculate" i get : 
+66,94 for the ppm
Tune at 9995000hz

But the BF signal appear no to 1khz but at 1350hz.

Maybe I'm doing it wrong but I followed a youtube video to remind myself how to do it and it doesn't have the same effect.

Many Thanks.

**Comment by ik1xpv** [comment]
You are right, Thanks.
This if the first of the known issue we have see  https://github.com/ik1xpv/ExtIO_sddc/releases/tag/v1.1
" - The reference frequency correction via HDSDR -> Options -> Calibration Settings ->LO Frequency Calibration doesn't work correctly. This problem will be addressed in the next release."

**Comment by F4HTB** [comment]
Hello, 
know you if it's possible to set ppm correction in another way?

**Comment by ik1xpv** [comment]
In v1.01 https://github.com/ik1xpv/ExtIO_sddc/releases/tag/v1.01 I used a control in ExtIO dialog.
I we will not able to solve in other way we will go back to such a solution.
Note that RX888 has internal trimmer to adjust the reference.

**Comment by hayguen** [comment]
@ik1xpv  think you need to go back to that solution!
HDSDR's correction is linear only .. thus, it will only work for HF (direct ADC conversion).
on VHF, when the tuner comes in, HDSDR would require additional knowledge of the structure .. which it hasn't.

but: this does not explain this error with the 9.996MHZ beacon.

**Comment by F4HTB** [comment]
It's the green one?

![aaaa](https://user-images.githubusercontent.com/18350938/103009026-ef907a00-452d-11eb-856c-70eb1abb5b59.png)

**Comment by ik1xpv** [comment]
Hayati you are right.  we have to do it in the ExtIO dialog.
Olivier, yes that is the trimmer I used. Of course be careful and use a very small trimmer ;-)

**Comment by hayguen** [comment]
@F4HTB : can you please reset and repeat the calibration?
this time, please have the LO just 1 kHz away from the tune frequency, whilst calibration!
and then report both frequencies and what frequency is reported before and after doing AM sync.
then, after the calibration, have the LO multiple MHz away .. but tune to the same frequency .. what synced Tune frequency is reported then?

@ik1xpv : i suppose, that the samplerate error, which is not calibrated .. does produce additional error .. right?

**Comment by ik1xpv** [comment]
Hi Hayati,
Yes you are right.  The sample rate error, which is not calibrated,
produces additional error.
HF103 has a fixed xtal oscillator. To compensate for the reference error in
v1.01 I asked the User after writing the ppm error to restart HDSDR to used
the new
sample rate with the correction.
Oscar

**Comment by hayguen** [comment]
Hi Oscar,
meanwhile i've tested myself, what i asked to F4HTB.
it's what i expected/feared:
the huge samplerate is not calibrated - just the LO frequency gets calibrated ..
thus, the reported samplerate to HDSDR would need to be adjusted.

it's nice to have a possibility to calibrate with a screwdriver .. but that would require opening the case .. not so ideal (for me)

**Comment by ik1xpv** [comment]
You are right.  Somehow we will do it :-)

**Comment by howard0su** [comment]
one problem of HDSDR is that it displays the raw sample rate like 63999999 which is a bit ugly on UI. If HDSDR can display it wrapped as 64M, it will be great.

I think we may need to add back the logic to calibrate ADC rate.

**Comment by ik1xpv** [comment]
Fixed in https://github.com/ik1xpv/ExtIO_sddc/tree/v1.2RC1
