### ISSUE TITLE
Set 64mhz bandwith in HDSDR was it possible?

### ISSUE THREAD

**Issue by F4HTB** [ik1xpv/ExtIO_sddc#111]
Hello,

Receiver: RX888
Software: HDSDR v2.80 installer with OmniRig V2 support. (March 19, 2020)
DLL: ExtIO_sddc_v1.1RC1.zip from https://github.com/ik1xpv/ExtIO_sddc/releases/download/v1.1/ExtIO_sddc_v1.1RC1.zip
OS: Windows 10 1909

When i set 128M (i think for 128msps) for the ADC, i dont find how to have 64mhz of Bandwidth in hdsdr.
Normaly i clic on "Bandwidth [F6]" and on the select menu "Input" i must have 6400000, but i see 32000000 only.

![aaa](https://user-images.githubusercontent.com/18350938/102718037-dc876b00-42dd-11eb-8cbb-9724d74dfd35.png)

Many Thanks for help.

**Comment by ik1xpv** [comment]
You are right.
Now you can use the combo box where there is now the label 32M if you press the down arrow you can select 64M.
We have to update the HDSDR combo box list too.
Many thanks to you for the report.

**Comment by howard0su** [comment]
I believe this is a bug in HDSDR. Driver already sent the notification to HDSDR when switch to 128M sampling rate. I tried to contact the author of HDSDR on the same issue two weeks ago but no response so far.

One possible fix is that we already populate the 64M choice at startup. When the user choose 64M bandwidth, switch to 128M adc sample rate automatically.

**Comment by ik1xpv** [comment]
Howard I think you are right.  I  had to ask the User to switch off and on again the HDSDR to accept the new rates when I  adjusted the ADC rate value in HF103.

**Comment by howard0su** [comment]
Confirmed that this is a bug in HDSDR. HDSDR team may address this in the future release.
