### ISSUE TITLE
Addition of unwanted signals depending on the selected reception mode.

### ISSUE THREAD

**Issue by F4HTB** [ik1xpv/ExtIO_sddc#112]
Hello,

Receiver: RX888
Software: HDSDR v2.80 installer with OmniRig V2 support. (March 19, 2020)
DLL: ExtIO_sddc_v1.1RC1.zip from https://github.com/ik1xpv/ExtIO_sddc/releases/download/v1.1/ExtIO_sddc_v1.1RC1.zip
OS: Windows 10 1909

This phenomenon appears in the high frequencies of HF. Between 22 and 32 mhz.
When I use my FM reception mode, there are less unwanted lines than in USB.
See the pictures.
![aaa](https://user-images.githubusercontent.com/18350938/102718020-b4980780-42dd-11eb-9978-d90afe949700.png)

Many Thanks.

**Comment by ik1xpv** [comment]
This is new to me.  I have no idea of the cause,
Do you think your antenna could pick-up some noise from pc ?
Many thanks for your precise report.

**Comment by F4HTB** [comment]
I thought about it but I tested on two antennas and I have the same problem. Maybe it's from my computer.
If someone else has the problem I think it's software otherwise if no one else sees it, are we going to assume that it is from my hardware?

:-D

**Comment by ik1xpv** [comment]
I will try to reproduce it here. 
The Extio.dll software in principle ignores the demodulation settings. 
Nevertheless do you know how much the electrons would laugh if they knew what we thought of them... :-)

**Comment by F4HTB** [comment]
Okey It real come from my laptop...
Has anyone ever tried trying LC filters on the RX888 power supply?

**Comment by ik1xpv** [comment]
Are you using the USB cable with ferrite filter ?
Would you please check if you have the spurs with the antenna disconnected or not.
Please verify also if you get them when the laptop is running on battery.
What happens if you ground the antenna cable shield.

**Comment by F4HTB** [comment]
Are you using the USB cable with ferrite filter ?
   Yes=>Litle effect.
Would you please check if you have the spurs with the antenna disconnected or not.
   No=>No changes 
Please verify also if you get them when the laptop is running on battery.
   Yes=>Classic thing...
What happens if you ground the antenna cable shield.
   No=>No change

You'll laugh once more, it seems like it comes when I use my Logitech "ConferenceCam BCC950". A product supposed to be professional ...

Problem solves!
By the way, if you ever have an address on ebay to buy a 5v injector in the usb cable to put a linear power supply, I am interested.

73, F4HTB!

**Comment by ik1xpv** [comment]
I'm happy you find the cause! 
I do not know manufacturer of such power splitter.

73, Oscar
