### ISSUE TITLE
more fine RBW 

### ISSUE THREAD

**Issue by F4HTB** [ik1xpv/ExtIO_sddc#113]
Hello, 

Receiver: RX888
Software: HDSDR v2.80 installer with OmniRig V2 support. (March 19, 2020)
DLL: ExtIO_sddc_v1.1RC1.zip from https://github.com/ik1xpv/ExtIO_sddc/releases/download/v1.1/ExtIO_sddc_v1.1RC1.zip
OS: Windows 10 1909

When we start first time we have RBW 62 Hz, after change we can't set it under 122.1Hz.
Can we made something to get more thinness?

Many Thanks, 

73 F4HTB

**Comment by ik1xpv** [comment]
The RBW is selected in HDSDR and the value can be changed using the arrows near the RBW label. The minimum and maximum value depend on the sampling rate SR that HDSDR uses.
If you select SR  32 Msps the minimum RBW is 122,1 Hz.  If you want to go to 61 Hz you have to use a 16 Msps SR or lower,
If you switch from SR lower to 32 Msps one the minimum resolution is automatically modified by HDSDR  to 122.1Hz
You have to decrease SR to 2Msps to get a RBW minimum of 7.6 Hz

**Comment by F4HTB** [comment]
Yes, it surprised me that at the first start it was on 62 (or something like that.)
I'll try to email them to see if we can break this restriction. Maybe they don't use sliding buffers.
