### ISSUE TITLE
Sounds like clipping, on strong stations 

### ISSUE THREAD

**Issue by ik1xpv** [ik1xpv/ExtIO_sddc#120]
Mark Pettifor described this bug in  https://groups.io/g/NextGenSDRs/message/318
and made the following investigation, making comparison with v1.01.see following messages.I thank you a lot for pointing it out.I replicated the problem using my sine wave generator -25 dBm level, 64MHz ADCclock, 32M sample rate , -10dB att.
![image](https://user-images.githubusercontent.com/9883800/103148229-d79f3d00-475d-11eb-9d98-f26a7ade4d0d.png)
Hereafter the old v1.01 dll
![image](https://user-images.githubusercontent.com/9883800/103148254-13d29d80-475e-11eb-824f-b00dd07673a1.png)
The problem is difficult to notice on low level signals coming from the antenna.It seems to me like there is some problem in ordering sample's buffers ?

**Comment by howard0su** [comment]
Fixed in master
