### ISSUE TITLE
HF signals in VHF/UHF and vice versa

### ISSUE THREAD

**Issue by Ploends** [ik1xpv/ExtIO_sddc#177]
I use a rx888 mk2 with HDSDR 2.80 with two separate antennas connected to it. One for HF, the other one for VHF/UHF.
When I start in HF and tune into VHF/UHF the lower frequency HF signal pattern is visible in the 8 MHz wide VHF/UHF window. The signals are even readable at these higher frequencies in AM mode. The stronger the amplification is set for HF, the stronger these signals appear also in the VHF/UHF window. 
The opposite effect can also be observed. When the amplification in VHF/UHF is turned on, strong VHF/UHF signals are visible in the low frequency part of the HF spectrum but they disappear when the UHF/VHF amplification is turned down again.
I have not yet observed this with other SDRs and wonder if this effect is software related or indicates a hardware issue with my mk2 unit ?

**Comment by ik1xpv** [comment]
Thanks for detailed report. I made the test setup in picture. I use a wire antenna both for HF and VHF. I placed a 3 dB splitter at the input. The HF input pass thought a 32 MHz LPF filter as I know that that RX888 mk2 has a 64 MHz LPF that does not match the 64 MHz sampling.  
![image](https://user-images.githubusercontent.com/9883800/110449667-b8f4e500-80c2-11eb-81f2-194dc5b43218.png)
I did not noticed cross-talk HF-> VHF or VHF->HF  setting gains to max.
Here in Torino we have  strong FM stations and if I do not use a LPF that matches the ADC rate/2 the alias of FM band is very visible in HF. 
I will keep issue open to keep testing of this configuration.

**Comment by ik1xpv** [comment]
Update!. I'm able to replicate the bug !!
The key point is to put all the gains to max.  We are looking for the fix.
Thanks again for signalling it!

**Comment by Ploends** [comment]
Thanks for picking this up so quickly.

Marcus

**Comment by howard0su** [comment]
This should be fixed via #183 

Please try to download the test bits to verify if it fixes your problem.
