### ISSUE TITLE
VHF background pattern

### ISSUE THREAD

**Issue by Ploends** [ik1xpv/ExtIO_sddc#188]
The new extio file has clearly solved the problem of VHF singals in HF spectrum. Well done !
On my RX888 MKII unit I can still observe a significant amount of HF signals travelling into VHF and 
creating a background pattern. I have attached a few photos to explain what I observe:
The first photo shows my HF spectrum at 32 MHz bandwidth. RF is set to 0 and IF is set to -25.
All is fine.

![Photo 1](https://user-images.githubusercontent.com/80283688/111771203-501c2280-88a3-11eb-81aa-61f31bc6bd3a.jpg)

The second photo shows the VHF spectrum, also at 32 MHz bandwidth, that I see when I tune into 
the FM broadcasting area.
The RF in VHF is set to 0. The IF is -5. One can see some week VHF signals and a pattern of a lot of HF 
signals that seem to be mirrored into VHF.

![Photo 2](https://user-images.githubusercontent.com/80283688/111771334-72ae3b80-88a3-11eb-9863-e504db532308.jpg)

When I tune within the VHF spectrum, the VHF signals move as expected but the background signal 
pattern remains the same. The signals of the background pattern do not not move.

![Photo 3](https://user-images.githubusercontent.com/80283688/111771659-dc2e4a00-88a3-11eb-945e-9ddb2917fa89.jpg)

On the final photo one can see that the background pattern disappears completely when I 
disconnect the HF antenna. Then only the VHF signals remain.

![Photo 4](https://user-images.githubusercontent.com/80283688/111772193-80b08c00-88a4-11eb-85c9-d183ddcd1bf0.jpg)

Not sure if this is a Bug or an issue with my MKII unit ?

**Comment by ik1xpv** [comment]
Many thanks for the detailed report. The today Howard's PR #187 possibly will reduce the problem. 
May you please made a test with the code you find here at page  [ Actions](https://github.com/ik1xpv/ExtIO_sddc/actions/runs/667257927) 
In the bottom of page you find the compiled  extio-package.zip.
Thanks in advance,
Oscar

**Comment by Ploends** [comment]
Dear Oscar,
Thanks for your quick reply. Unfortunately the situation is still the same even with the Extio  package from the link that you provided.
Regards

Marcus

**Comment by ik1xpv** [comment]
Hi Marcus, 
Please test this code [#189](https://github.com/ik1xpv/ExtIO_sddc/actions/runs/675352806)
In the bottom of page you find the compiled extio-package.zip.
Possibly it will decrease the crosstalk by some 30 dB.
BR  
Oscar

**Comment by Ploends** [comment]
Hi Oscar,
this is indeed a massive improvement !
Only the 5 strongest AM signal are still visible on the right sight of the 8 MHz VHF window.
These 5 signals are the strongest AM broadcasting stations that I can receive here in Edinburgh.

Thanks

Marcus

**Comment by howard0su** [comment]
I will mark this as resolved unless there is objection.
