### ISSUE TITLE
SDR# crash

### ISSUE THREAD

**Issue by Boxnut** [ik1xpv/ExtIO_sddc#202]
When I select extio_sddc in SDR#, it tries to connect and crashes. This is my preferred software.
Using this with HDSDR, the output is too bad for use, especially decoders.
I would just like to have this working properly on SDR#.
Radio is RX888 mkII
SDRsharper (v0.5K)
ExtIO_sddc.dll Version "V1.2.0" date 18/3/2021
Thankyou Oscar

**Comment by Boxnut** [comment]
The screenshots
![Screenshot (447)](https://user-images.githubusercontent.com/55829238/119258583-8ae25580-bb87-11eb-9aa3-7482f6ac75eb.png)
![Screenshot (448)](https://user-images.githubusercontent.com/55829238/119258594-9897db00-bb87-11eb-8198-3db3ad377a1a.png)

**Comment by ik1xpv** [comment]
Thanks for feedback. I developed ExtIO_sddc with HDSDR.  It will take some time to look at the new environment. :-)

**Comment by ik1xpv** [comment]
I was not able to find that version v 0.5k and I downloaded SDRsharper v.1.1.1 that I tested with [https://github.com/ik1xpv/ExtIO_sddc/releases/tag/v1.2.0](https://github.com/ik1xpv/ExtIO_sddc/releases/tag/v1.2.0):
![image](https://user-images.githubusercontent.com/9883800/119402743-a8293800-bcdd-11eb-8229-1512ea4a4bee.png).
You need to config the ExtIO clock ( I used 64MHz) and select IF bandwidth 16MHz or lower before pressing play button.
I noticed that SDRsharper is not able to run with IF bandwidth > 16MHz.
HDSDR on the same pc runs 128MHz clock and 64MHz IF bandwidth.

**Comment by Boxnut** [comment]
Thank you Oscar, I will make these changes and test the outcome.I tried finding a newer version of SDRsharper and unable to find a download for V1,1,1I never get to the setting before crashing, so let me find the newer version and I will keep you posted.Thank you for your time.

    On Monday, May 24, 2021, 2:26:35 PM MDT, Oscar Steila ***@***.***> wrote:  
 
 


I was not able to find that version v 0.5k and I downloaded SDRsharper v.1.1.1 that I tested with https://github.com/ik1xpv/ExtIO_sddc/releases/tag/v1.2.0:
.
You need to config the ExtIO clock ( I used 64MHz) and select IF bandwidth 16MHz or lower before pressing play button.
I noticed that SDRsharper is not able to run with IF bandwidth > 16MHz.
HDSDR on the same pc runs 128MHz clock and 64MHz IF bandwidth.

**Comment by Boxnut** [comment]
This does function with HDSDR, but on my machine the performance is useless. Never had acceptable performance with this even with other radios, why I would like to see this work with SDR sharper.Thanks for your time

    On Monday, May 24, 2021, 4:05:19 AM MDT, Oscar Steila ***@***.***> wrote:  
 
 


Thanks for feedback. I developed ExtIO_sddc with HDSDR. It will take some time to look at the new environment. :-)
