### ISSUE TITLE
error while compiling SDDC_FX3 on Ubuntu

### ISSUE THREAD

**Issue by cozycactus** [ik1xpv/ExtIO_sddc#206]
arm-none-eabi-ld obj/cyfx_gcc_startup.o obj/cyfxtx.o obj/DebugConsole.o obj/i2cmodule.o obj/RunApplication.o obj/StartStopApplication.o obj/StartUP.o obj/Support.o obj/USBdescriptor.o obj/USBhandler.o obj/Si5351.o obj/adf4351.o obj/rd5815.o obj/tuner_r82xx.o obj/pcal6408a.o obj/hf103.o obj/bbrf103.o obj/rx888.o obj/rx999.o obj/rx888r2.o obj/rx888r3.o obj/rxlucy.o --entry CyU3PFirmwareEntry -L ../SDK/fw_lib/1_3_4/fx3_release -lcyu3sport -lcyu3lpp -lcyfxapi -lcyu3threadx /usr/lib/arm-none-eabi/lib/libc.a /usr/lib/gcc/arm-none-eabi/4.8.1/libgcc.a  -T ../SDK/fw_build/fx3_fw/fx3_512k.ld -d --gc-sections --no-wchar-size-warning -Map SDDC_FX3.map -o SDDC_FX3.elf
arm-none-eabi-ld: cannot find /usr/lib/arm-none-eabi/lib/libc.a: No such file or directory
arm-none-eabi-ld: cannot find /usr/lib/gcc/arm-none-eabi/4.8.1/libgcc.a: No such file or directory
make: *** [makefile:76: SDDC_FX3.elf] Error 1

**Comment by fventuri** [comment]
@cozycactus 
that error message makes me think something is not right in your Ubuntu installation of the 'FX3 SDK for Linux platforms' (item 4 in the 'EZ-USB FX3 Software Development Kit': https://www.cypress.com/documentation/software-and-drivers/ez-usb-fx3-software-development-kit).

Can you run these 'find' commands to figure out where those two static libraries are located on your system?
```
find /usr -name libc.a | grep arm
find /usr -name libgcc.a | grep arm
find /opt -name libc.a | grep arm
find /opt -name libgcc.a | grep arm
```
If those commands return no results, I would reinstall the EZ-USB FX3 SDK for Linux following the instructions from the README (https://github.com/ik1xpv/ExtIO_sddc#build-instructions-for-firmware).

Hope this helps,
Franco

**Comment by cozycactus** [comment]
ruslan@ruslan-OptiPlex-7010:~/ExtIO_sddc/SDDC_FX3$ find /usr -name libc.a | grep arm
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v7-m/nofp/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v8-a+simd/softfp/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v8-a+simd/hard/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v7+fp/softfp/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v7+fp/hard/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v8-m.main+fp/softfp/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v8-m.main+fp/hard/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v7e-m/nofp/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v8-m.main+dp/softfp/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v8-m.main+dp/hard/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v7-a+fp/softfp/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v7-a+fp/hard/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v7e-m+fp/softfp/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v7e-m+fp/hard/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v7/nofp/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v7e-m+dp/softfp/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v7e-m+dp/hard/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v7-a+simd/softfp/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v7-a+simd/hard/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v7-a/nofp/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v7ve+simd/softfp/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v7ve+simd/hard/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v8.1-m.main+mve/hard/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v6-m/nofp/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v8-m.main/nofp/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v8-a/nofp/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v7-r+fp.sp/softfp/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v7-r+fp.sp/hard/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/v8-m.base/nofp/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/thumb/nofp/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/arm/v5te/softfp/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/arm/v5te/hard/libc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/arm-none-eabi/lib/libc.a
ruslan@ruslan-OptiPlex-7010:~/ExtIO_sddc/SDDC_FX3$ find /usr -name libgcc.a | grep arm
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v7-m/nofp/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v8-a+simd/softfp/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v8-a+simd/hard/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v7+fp/softfp/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v7+fp/hard/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v8-m.main+fp/softfp/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v8-m.main+fp/hard/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v7e-m/nofp/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v8-m.main+dp/softfp/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v8-m.main+dp/hard/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v7-a+fp/softfp/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v7-a+fp/hard/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v7e-m+fp/softfp/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v7e-m+fp/hard/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v7/nofp/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v7e-m+dp/softfp/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v7e-m+dp/hard/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v7-a+simd/softfp/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v7-a+simd/hard/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v7-a/nofp/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v7ve+simd/softfp/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v7ve+simd/hard/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v8.1-m.main+mve/hard/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v6-m/nofp/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v8-m.main/nofp/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v8-a/nofp/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v7-r+fp.sp/softfp/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v7-r+fp.sp/hard/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/v8-m.base/nofp/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/thumb/nofp/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/arm/v5te/softfp/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/arm/v5te/hard/libgcc.a
/usr/share/gcc-arm-none-eabi-10.3-2021.07/lib/gcc/arm-none-eabi/10.3.1/libgcc.a

**Comment by fventuri** [comment]
@cozycactus - given the output of your 'find' commands, I think that in the SDDC_FX3 firmware build (https://github.com/ik1xpv/ExtIO_sddc#build-instructions-for-firmware), you have to set those three environment variables to something like this:

```
export FX3FWROOT=<installation path>
export ARMGCC_INSTALL_PATH=/usr/share/gcc-arm-none-eabi-10.3-2021.07
export ARMGCC_VERSION=10.3.1
```
(they might need to be slightly tweaked; if the build still fails with these new values for the environment variables, you should be able to see what they should be set to in your Ubuntu computer).

Franco

**Comment by cozycactus** [comment]
Thank  you! it compiles now
