### ISSUE TITLE
RX888 runs offline with virtual signals in demo mode ??

### ISSUE THREAD

**Issue by m1ctk** [ik1xpv/ExtIO_sddc#211]
Anyone tell me why I get this error with windows 10 64bit ? correct driver is installed as is the two files needed

**Comment by ik1xpv** [comment]
Hi,
The virtual signal mode was present in the early release of ExtIO_sddc.dll. It is no more present from version 1.x

Please use the latest release  1.20 [https://github.com/ik1xpv/ExtIO_sddc/releases/latest](https://github.com/ik1xpv/ExtIO_sddc/releases/latest)
The required files are   ExtIO_SDDC.dll    libfftw3f-3.dll 
They can be downloaded from the archive SDDC_EXTIO.zip at [https://github.com/ik1xpv/ExtIO_sddc/releases/download/v1.2.0/SDDC_EXTIO.ZIP](https://github.com/ik1xpv/ExtIO_sddc/releases/download/v1.2.0/SDDC_EXTIO.ZIP)

Or even better the prerelease v1.3.0RC1 the archive is at  [https://github.com/ik1xpv/ExtIO_sddc/releases/download/v1.3.0RC1/extio-package.zip](https://github.com/ik1xpv/ExtIO_sddc/releases/download/v1.3.0RC1/extio-package.zip)
The application HDSDR.exe  v 2.0 or v2.81 can be downloaded from [https://www.hdsdr.de/](https://www.hdsdr.de/)

Connect the BBRF103 or RX888 without running HDSDR.  It must be seen in the connected USB devices  as "Cypress FX3 Boot Loader Device" If not there is a problem with the Cypress driver or hardware (by the way is the port USB 3.0?)

Oscar

**Comment by m1ctk** [comment]
Thanks a lot now running in HDSDR but no audio ? SDR sharp 1732 works but I can't adjust the gain - it's deaf atm. SDR console 3.0.24 what to do ? Latest version works ?

**Comment by m1ctk** [comment]
Update : ok SDR sharp works ok but how do I adjust the IF bandwidth down from 32MB ? Also I keep having to change settings each time I close down / start up again

**Comment by ik1xpv** [comment]
The max IF bandwidth processed  depends also by the application.

While HDSDR  processes 32 MHz in real time or 64 MHz when the setting of adc clk is 128MHz,
some application are able to manage only slower rate and
some others can manage 32 MHz signal stream while the real time display of IF spectrogram is limited to a narrow band.

Settings are managed by host application with the EXTIO_API _ExtIoGetSetting_  and  _ExtIoSetSetting_ 
If the application do not uses them the setting are not saved, 
See [https://github.com/ik1xpv/ExtIO_sddc/blob/master/ExtIO_sddc/ExtIO_sddc.h](https://github.com/ik1xpv/ExtIO_sddc/blob/master/ExtIO_sddc/ExtIO_sddc.h)

**Comment by m1ctk** [comment]
OK anyway all 3 progs working now. Most compatible is SDR console 3.1 followed by HDSDR, SDR sharp is all over the place certainly with VHF for weather sats but MW is good
