### ISSUE TITLE
Help with building firmware

### ISSUE THREAD

**Issue by cozycactus** [ik1xpv/ExtIO_sddc#222]
cozy@cozy-Z590-UD-AC:~/ExtIO_sddc/SDDC_FX3$ make
mkdir -p obj
arm-none-eabi-gcc  -Wall -c -mcpu=arm926ej-s -mthumb-interwork -o obj/cyfx_gcc_startup.o cyfx_gcc_startup.S
arm-none-eabi-gcc -g -DTX_ENABLE_EVENT_TRACE -DDEBUG -DCYU3P_FX3=1 -D__CYU3P_TX__=1 -I. -I/home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/inc -I./radio -I./driver -Os -Wall -mcpu=arm926ej-s -mthumb-interwork -ffunction-sections -fdata-sections -c -o obj/cyfxtx.o cyfxtx.c 
arm-none-eabi-gcc -g -DTX_ENABLE_EVENT_TRACE -DDEBUG -DCYU3P_FX3=1 -D__CYU3P_TX__=1 -I. -I/home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/inc -I./radio -I./driver -Os -Wall -mcpu=arm926ej-s -mthumb-interwork -ffunction-sections -fdata-sections -c -o obj/DebugConsole.o DebugConsole.c 
arm-none-eabi-gcc -g -DTX_ENABLE_EVENT_TRACE -DDEBUG -DCYU3P_FX3=1 -D__CYU3P_TX__=1 -I. -I/home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/inc -I./radio -I./driver -Os -Wall -mcpu=arm926ej-s -mthumb-interwork -ffunction-sections -fdata-sections -c -o obj/i2cmodule.o i2cmodule.c 
arm-none-eabi-gcc -g -DTX_ENABLE_EVENT_TRACE -DDEBUG -DCYU3P_FX3=1 -D__CYU3P_TX__=1 -I. -I/home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/inc -I./radio -I./driver -Os -Wall -mcpu=arm926ej-s -mthumb-interwork -ffunction-sections -fdata-sections -c -o obj/RunApplication.o RunApplication.c 
arm-none-eabi-gcc -g -DTX_ENABLE_EVENT_TRACE -DDEBUG -DCYU3P_FX3=1 -D__CYU3P_TX__=1 -I. -I/home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/inc -I./radio -I./driver -Os -Wall -mcpu=arm926ej-s -mthumb-interwork -ffunction-sections -fdata-sections -c -o obj/StartStopApplication.o StartStopApplication.c 
arm-none-eabi-gcc -g -DTX_ENABLE_EVENT_TRACE -DDEBUG -DCYU3P_FX3=1 -D__CYU3P_TX__=1 -I. -I/home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/inc -I./radio -I./driver -Os -Wall -mcpu=arm926ej-s -mthumb-interwork -ffunction-sections -fdata-sections -c -o obj/StartUP.o StartUP.c 
arm-none-eabi-gcc -g -DTX_ENABLE_EVENT_TRACE -DDEBUG -DCYU3P_FX3=1 -D__CYU3P_TX__=1 -I. -I/home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/inc -I./radio -I./driver -Os -Wall -mcpu=arm926ej-s -mthumb-interwork -ffunction-sections -fdata-sections -c -o obj/Support.o Support.c 
arm-none-eabi-gcc -g -DTX_ENABLE_EVENT_TRACE -DDEBUG -DCYU3P_FX3=1 -D__CYU3P_TX__=1 -I. -I/home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/inc -I./radio -I./driver -Os -Wall -mcpu=arm926ej-s -mthumb-interwork -ffunction-sections -fdata-sections -c -o obj/USBdescriptor.o USBdescriptor.c 
arm-none-eabi-gcc -g -DTX_ENABLE_EVENT_TRACE -DDEBUG -DCYU3P_FX3=1 -D__CYU3P_TX__=1 -I. -I/home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/inc -I./radio -I./driver -Os -Wall -mcpu=arm926ej-s -mthumb-interwork -ffunction-sections -fdata-sections -c -o obj/USBhandler.o USBhandler.c 
arm-none-eabi-gcc -g -DTX_ENABLE_EVENT_TRACE -DDEBUG -DCYU3P_FX3=1 -D__CYU3P_TX__=1 -I. -I/home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/inc -I./radio -I./driver -Os -Wall -mcpu=arm926ej-s -mthumb-interwork -ffunction-sections -fdata-sections -c -o obj/Si5351.o driver/Si5351.c 
arm-none-eabi-gcc -g -DTX_ENABLE_EVENT_TRACE -DDEBUG -DCYU3P_FX3=1 -D__CYU3P_TX__=1 -I. -I/home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/inc -I./radio -I./driver -Os -Wall -mcpu=arm926ej-s -mthumb-interwork -ffunction-sections -fdata-sections -c -o obj/adf4351.o driver/adf4351.c 
arm-none-eabi-gcc -g -DTX_ENABLE_EVENT_TRACE -DDEBUG -DCYU3P_FX3=1 -D__CYU3P_TX__=1 -I. -I/home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/inc -I./radio -I./driver -Os -Wall -mcpu=arm926ej-s -mthumb-interwork -ffunction-sections -fdata-sections -c -o obj/rd5815.o driver/rd5815.c 
arm-none-eabi-gcc -g -DTX_ENABLE_EVENT_TRACE -DDEBUG -DCYU3P_FX3=1 -D__CYU3P_TX__=1 -I. -I/home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/inc -I./radio -I./driver -Os -Wall -mcpu=arm926ej-s -mthumb-interwork -ffunction-sections -fdata-sections -c -o obj/tuner_r82xx.o driver/tuner_r82xx.c 
arm-none-eabi-gcc -g -DTX_ENABLE_EVENT_TRACE -DDEBUG -DCYU3P_FX3=1 -D__CYU3P_TX__=1 -I. -I/home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/inc -I./radio -I./driver -Os -Wall -mcpu=arm926ej-s -mthumb-interwork -ffunction-sections -fdata-sections -c -o obj/pcal6408a.o pcal6408a.c 
arm-none-eabi-gcc -g -DTX_ENABLE_EVENT_TRACE -DDEBUG -DCYU3P_FX3=1 -D__CYU3P_TX__=1 -I. -I/home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/inc -I./radio -I./driver -Os -Wall -mcpu=arm926ej-s -mthumb-interwork -ffunction-sections -fdata-sections -c -o obj/hf103.o radio/hf103.c 
arm-none-eabi-gcc -g -DTX_ENABLE_EVENT_TRACE -DDEBUG -DCYU3P_FX3=1 -D__CYU3P_TX__=1 -I. -I/home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/inc -I./radio -I./driver -Os -Wall -mcpu=arm926ej-s -mthumb-interwork -ffunction-sections -fdata-sections -c -o obj/bbrf103.o radio/bbrf103.c 
arm-none-eabi-gcc -g -DTX_ENABLE_EVENT_TRACE -DDEBUG -DCYU3P_FX3=1 -D__CYU3P_TX__=1 -I. -I/home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/inc -I./radio -I./driver -Os -Wall -mcpu=arm926ej-s -mthumb-interwork -ffunction-sections -fdata-sections -c -o obj/rx888.o radio/rx888.c 
arm-none-eabi-gcc -g -DTX_ENABLE_EVENT_TRACE -DDEBUG -DCYU3P_FX3=1 -D__CYU3P_TX__=1 -I. -I/home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/inc -I./radio -I./driver -Os -Wall -mcpu=arm926ej-s -mthumb-interwork -ffunction-sections -fdata-sections -c -o obj/rx999.o radio/rx999.c 
arm-none-eabi-gcc -g -DTX_ENABLE_EVENT_TRACE -DDEBUG -DCYU3P_FX3=1 -D__CYU3P_TX__=1 -I. -I/home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/inc -I./radio -I./driver -Os -Wall -mcpu=arm926ej-s -mthumb-interwork -ffunction-sections -fdata-sections -c -o obj/rx888r2.o radio/rx888r2.c 
arm-none-eabi-gcc -g -DTX_ENABLE_EVENT_TRACE -DDEBUG -DCYU3P_FX3=1 -D__CYU3P_TX__=1 -I. -I/home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/inc -I./radio -I./driver -Os -Wall -mcpu=arm926ej-s -mthumb-interwork -ffunction-sections -fdata-sections -c -o obj/rx888r3.o radio/rx888r3.c 
arm-none-eabi-gcc -g -DTX_ENABLE_EVENT_TRACE -DDEBUG -DCYU3P_FX3=1 -D__CYU3P_TX__=1 -I. -I/home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/inc -I./radio -I./driver -Os -Wall -mcpu=arm926ej-s -mthumb-interwork -ffunction-sections -fdata-sections -c -o obj/rxlucy.o radio/rxlucy.c 
arm-none-eabi-ld obj/cyfx_gcc_startup.o obj/cyfxtx.o obj/DebugConsole.o obj/i2cmodule.o obj/RunApplication.o obj/StartStopApplication.o obj/StartUP.o obj/Support.o obj/USBdescriptor.o obj/USBhandler.o obj/Si5351.o obj/adf4351.o obj/rd5815.o obj/tuner_r82xx.o obj/pcal6408a.o obj/hf103.o obj/bbrf103.o obj/rx888.o obj/rx999.o obj/rx888r2.o obj/rx888r3.o obj/rxlucy.o --entry CyU3PFirmwareEntry -L /home/cozy/Cypress/cyfx3sdk/fw_lib/1_3_4/fx3_release -lcyu3sport -lcyu3lpp -lcyfxapi -lcyu3threadx "$ARMGCC_INSTALL_PATH"/arm-none-eabi/lib/libc.a "$ARMGCC_INSTALL_PATH"/lib/gcc/arm-none-eabi/10.3.1/libgcc.a  -T /home/cozy/Cypress/cyfx3sdk/fw_build/fx3_fw/fx3_512k.ld -d --gc-sections --no-wchar-size-warning -Map SDDC_FX3.map -o SDDC_FX3.elf
arm-none-eabi-ld: obj/RunApplication.o:/home/cozy/ExtIO_sddc/SDDC_FX3/RunApplication.c:36: multiple definition of `Qevent'; obj/DebugConsole.o:/home/cozy/ExtIO_sddc/SDDC_FX3/DebugConsole.c:36: first defined here
arm-none-eabi-ld: obj/StartStopApplication.o:/home/cozy/ExtIO_sddc/SDDC_FX3/StartStopApplication.c:16: multiple definition of `Qevent'; obj/DebugConsole.o:/home/cozy/ExtIO_sddc/SDDC_FX3/DebugConsole.c:36: first defined here
arm-none-eabi-ld: obj/USBhandler.o:/home/cozy/ExtIO_sddc/SDDC_FX3/USBhandler.c:66: multiple definition of `Qevent'; obj/DebugConsole.o:/home/cozy/ExtIO_sddc/SDDC_FX3/DebugConsole.c:36: first defined here
make: *** [makefile:76: SDDC_FX3.elf] Error 1

**Comment by vladisslav2011** [comment]
Hello.
That's multiple definition, that leads to UB.
Prepend all definitions of `Qevent` with `static` or all, but one, with `extern` to fix the error.

**Comment by cozycactus** [comment]
> Hello.
> 
> That's multiple definition, that leads to UB.
> 
> Prepend all definitions of `Qevent` with `static` or all, but one, with `extern` to fix the error.

Thanks. I will try . this fx3 sdk driving me crazy 😀
